softcore/rubrica/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.rubricas, name='rubricas'),
    path('<int:rubrica_id>/', views.ficha, name='ficha'),
    path('<int:rubrica_id>/edit/', views.edit_ficha, name='edit_ficha'),
    path('new/', views.new_ficha, name='new_ficha')
]

softcore/softcore/urls.py
from django.contrib import admin
from django.urls import include, path
from rubrica.views import AdminPageView

urlpatterns = [
    path('evaluadores/', include('usuarios.urls', namespace='evaluador')),
    path('evaluaciones/', include('evaluacion.urls')),
    path('rubricas/', include('rubrica.urls')),
    path('admin/', admin.site.urls),
    path('', AdminPageView.as_view(), name='index'),
]

softcore/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path('', views.evaluadores, name='evaluadores'),
    path('eliminar/<int:pk>/', views.eliminar_evaluador, name='eliminar_evaluador'),
]

softcore/usuarios/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.contrib.auth import get_user_model


class UserManager(BaseUserManager):
    def create_user(self, nombre, apellido, correo, password=None, profesor=False, admin=False):
        if not nombre:
            raise ValueError("Los usuarios deben tener un nombre")
        if not apellido:
            raise ValueError("Los usuarios deben tener un apellido")
        if not correo:
            raise ValueError("Los usuarios deben tener un correo")
        if not password:
            raise ValueError("Los usuarios deben tener un correo")

        user_obj = self.model(correo=self.normalize_email(correo))
        #user_obj= get_user_model().objects.create_user(correo = self.normalize_email(correo))

        user_obj.nombre = nombre
        user_obj.apellido = apellido
        user_obj.evaluador = True
        user_obj.profesor = profesor
        user_obj.admin = admin
        user_obj.set_password(password)
        user_obj.save()
        #user_obj.save(using = self._db)
        return user_obj

    def create_profesor_user(self, nombre, apellido, correo, password=None):
        user = self.create_user(nombre, apellido, correo, password, profesor=True)
        return user

    def create_superuser(self, nombre, apellido, correo, password=None):
        user = self.create_user(nombre, apellido, correo, password, profesor=True, admin=True)
        return user


# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    correo = models.EmailField(unique=True)
    nombre = models.CharField(max_length=80)
    apellido = models.CharField(max_length=80)

    evaluador = models.BooleanField(default=False)
    profesor = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'correo'

    REQUIRED_FIELDS = ['nombre', 'apellido']
    objects = UserManager()

    def __str__(self):
        return self.correo

    def get_nombre(self):
        return self.nombre

    def get_apellido(self):
        return self.apellido

    @property
    def is_evaluador(self):
        return self.evaluador

    @property
    def is_profesor(self):
        return self.profesor

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_staff(self):
        return self.admin

    @property
    def is_superuser(self):
        return self.admin

softcore/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('correo',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = '__all__'

softcore/usuarios/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404


from .models import CustomUser
# Create your views here.


class AdminPageView(TemplateView):
    template_name = 'index.html'


def evaluadores(request):
    if request.method == 'POST':
        username = request.POST['username']
        apellido = request.POST['apellido']
        email = request.POST['email']
        tipo_usuario = request.POST['tipo_usuario']

        if tipo_usuario == 'profesor':
            CustomUser.objects.create(correo=email, nombre=username,
                                      apellido=apellido, profesor=True, evaluador = True)
        else:
            CustomUser.objects.create(correo=email, nombre=username,
                                      apellido=apellido, evaluador=True)

    evaluadores_list = CustomUser.objects.all()
    context = {'evaluadores_list': evaluadores_list}
    return render(request, 'usuarios/evaluadores1.html', context)


def eliminar_evaluador(request, pk):
    CustomUser.objects.get(pk=pk).delete()
    evaluadores_list = CustomUser.objects.all()
    context = {'evaluadores_list': evaluadores_list}
    return HttpResponseRedirect(reverse('evaluador:evaluadores'))

softcore/usuarios/templates/usuarios/evaluadores.html
<!DOCTYPE html>
<html lang="es">
<title>Plataforma de evaluación-Evaluadores</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <!--Profile image -->
  <div class="w3-container">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:200px;width:200px" alt="Avatar"></p>
    <h3 class="w3-padding-64"><center><b>Usuario</b></center></h3>
  </div>
  <div class="w3-bar-block">
    <a href="#" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="#cursos" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="#evaluadores" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
      <a href="#rubricas" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
    <a href="#evaluaciones" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Usuario</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px"

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Evaluadores</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p><h3>Seleccione un evaluador</p></h2>
  </div>
<!---- evaluadores section--->

<div class="w3-quarter w3-margin-top">
  <button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow" style="min-height: 317px; max-width: 300px">
  <h3>Agregar evaluador nuevo</h3><br>
  <i class="fas fa-user-plus" style="font-size:80px;text-align: center; padding: 10px"></i>
  </button>
</div>
    <div id="agregar" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
        <div class="w3-center"><br>
            <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <form class="w3-container" action="/action_page.php">
        <div class="w3-section">
          <label><b>Nombre</b></label>
          <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="usrname" required>
          <label><b>Apellido</b></label>
          <input class="w3-input w3-border" type="text" placeholder="Ingrese apellido" name="psw" required>
            <label><b>Correo</b></label>
          <input class="w3-input w3-border" type="text" placeholder="Ingrese correo" name="secc" required>
          <button class="w3-button w3-block w3-red w3-section w3-padding" type="submit">Agregar</button>
        </div>
      </form>
      </div>
    </div>
  
    <!--cierre de cajas de cursos-->

</div>



{# {% if evaluadores_list %}

  {% for evaluador in evaluadores_list %}

    <button onclick="myFunction('Demo{{ evaluador.correo }}')" class="w3-btn w3-red w3-block w3-margin" style="width: 75%">
      <h3>
        {{ evaluador.nombre }}</h3>
    </button>
    
    <div id="Demo{{ evaluador.correo }}" class="w3-hide w3-container w3-pale-red w3-center w3-padding-large w3-margin" style="width: 75%">

      <div class="w3-container">
        <form method="get" action="{% url 'ficha' rubrica.id %}">
          <button type="submit" class="w3-button w3-large w3-margin-right w3-red w3-left w3-round">Ver</button>
        </form>
        <form method="get" action="{% url 'edit_ficha' rubrica.id %}">
          <button class="w3-button w3-large w3-red w3-left w3-round">Modificar</button>
        </form>
        <form method="post" action="">
          {% csrf_token %}
          <button type="submit" class="w3-button w3-large w3-red w3-right w3-round", name="id", value= "{{ rubrica.id }}">Eliminar</button>
        </form>
      </div>
    </div>
  {% endfor %}

{% else %}

{% endif %}
 #}



<!---
{% if evaluadores_list %}

  {% for evaluador in evaluadores_list %}

<div class="w3-row-padding w3-center w3-margin-top">
  <div class="w3-quarter w3-margin-top">
      <button onclick="document.getElementById('gestionar').style.display='block'" class="w3-card w3-container w3-hover-shadow" style="max-height:380px;min-height: 317px; max-width: 300px">
    <h3>Nombre y apellido</h3><br>
    <i class="fas fa-user-alt" style="font-size:100px"></i>
    <p>Correo</p>
    </button>
  </div>
      <div id="gestionar" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="width:300px">
          <div class="w3-center"><br>
              <span onclick="document.getElementById('gestionar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
          <div class="w3-margin">
            <button class="w3-button w3-red w3-section w3-padding:10px" type="submit">Modificar</button><br>
            <button class="w3-button w3-red w3-section w3-padding:10px" type="submit">Eliminar</button>
          </div>
        </div>
      </div>
      </div>
      {% endfor %}

      {% else %}
      
      {% endif %}
--->







<!--Cajas evaluadores-->
<!--- 
<div class="w3-row-padding w3-center w3-margin-top">
<div class="w3-quarter w3-margin-top">
    <button onclick="document.getElementById('gestionar').style.display='block'" class="w3-card w3-container w3-hover-shadow" style="max-height:380px;min-height: 317px; max-width: 300px">
  <h3>Nombre y apellido</h3><br>
  <i class="fas fa-user-alt" style="font-size:100px"></i>
  <p>Correo</p>
  </button>
</div>
    <div id="gestionar" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="width:300px">
        <div class="w3-center"><br>
            <span onclick="document.getElementById('gestionar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
        <div class="w3-margin">
          <button class="w3-button w3-red w3-section w3-padding:10px" type="submit">Modificar</button><br>
          <button class="w3-button w3-red w3-section w3-padding:10px" type="submit">Eliminar</button>
        </div>
      </div>
    </div>
    </div>
--->
<!--Caja de agregar-->
<!---
<div class="w3-quarter w3-margin-top">
  <button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow" style="min-height: 317px; max-width: 300px">
  <h3>Agregar evaluador nuevo</h3><br>
  <i class="fas fa-user-plus" style="font-size:80px;text-align: center; padding: 10px"></i>
  </button>
</div>
    <div id="agregar" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
        <div class="w3-center"><br>
            <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <form class="w3-container" action="/action_page.php">
        <div class="w3-section">
          <label><b>Nombre</b></label>
          <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="usrname" required>
          <label><b>Apellido</b></label>
          <input class="w3-input w3-border" type="text" placeholder="Ingrese apellido" name="psw" required>
            <label><b>Correo</b></label>
          <input class="w3-input w3-border" type="text" placeholder="Ingrese correo" name="secc" required>
          <button class="w3-button w3-block w3-red w3-section w3-padding" type="submit">Agregar</button>
        </div>
      </form>
      </div>
    </div>
    --->    
    <!--cierre de cajas de cursos-->

<!---</div>
--->
<!--cierre de contenido-->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

</script>

</body>

softcore/usuarios/templates/usuarios/evaluadores1.html
{% extends "index.html" %}

{% block content %}
	<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:60px;margin-right:0px">

  <!-- Portada -->
	<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
		<h1 class="w3-xxxlarge w3-text-red"><b>Evaluadores</b></h1>
		<hr style="width:50px;border:5px solid red" class="w3-round">
	</div>

	<div class="w3-row-padding w3-center w3-margin-top">
		<div class="w3-quarter w3-margin-top">
			<button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow" style="min-height: 317px; max-width: 300px">
				<h3>Agregar nuevo evaluador</h3><br>
				<i class="fas fa-user-plus" style="font-size:80px; text-align:center; 
				padding: 10px">
				</i>
			</button>
		</div>
	
		<div id="agregar" class="w3-modal">
			<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
				<div class="w3-center"><br>
				<span onclick="document.getElementById('agregar').style.display='none'" 
				class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
					<form class="w3-container" method="POST">{% csrf_token %}
						<div class="w3-section">
						<label><b>Nombre</b></label>
						<input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="username" required>
						<label><b>Apellido</b></label>
						<input class="w3-input w3-border" type="text" placeholder="Ingrese apellido" name="apellido" required>
						<label><b>Correo</b></label>
						<input class="w3-input w3-border" type="text" placeholder="Ingrese correo" name="email" required>
						<label><b>Tipo de usuario</b></label>
						<select class="w3-input w3-border" type="text" placeholder="Tipo de usuario" name="tipo_usuario" required>
							<option value="">----</option>
							<option value="profesor">profesor</option>
 							<option value="evaluador">evaluador</option>
						</select>
						<button class="w3-button w3-block w3-red w3-section w3-padding" type="submit">Agregar</button>
						</div>
					</form>
				</div>
			</div>
		<!--cierre de cajas de cursos-->
		</div>

	</div>

	<div class="w3-row-padding w3-center w3-margin-top">
		<table class="w3-table-all">
			<thead>
				<tr class="w3-red">
					<th>Nombre</th>
					<th>Apellido</th>
					<th>Correo</th>
					<th>Tipo de usuario</th>					
					<th>Acciones</th>
				</tr>
				<tbody>
					{% for usuario in evaluadores_list %}
					<tr>
						{% if not usuario.is_staff %}
							<td>{{ usuario.nombre }}</td>
							<td>{{ usuario.apellido }}</td>
							<td>{{ usuario.correo }}</td>
							{% if usuario.profesor %}
								<td>profesor</td>
							{% else %}
								<td>evaluador</td>
							{% endif %}
							<td>
								&nbsp;
								<a href="{% url 'evaluador:eliminar_evaluador' usuario.pk %}" class="w3-tooltip">
									<span style="position:absolute;left:0;bottom:18px" class="w3-text w3-tag">Eliminar</span><i class="fa fa-trash"></i></a>
								&nbsp;
								&nbsp;
								<a href="/admin/usuarios/customuser/{{usuario.pk}}/change/" class="w3-tooltip">
									<span style="position:absolute;left:0;bottom:18px" class="w3-text w3-tag">Editar</span><i class="fa fa-edit"></i></a>
							</td>
						{% endif %}
					</tr>
					{% endfor %}
				</tbody>
			</thead>
		</table>

	</div>



	

</div>
{% endblock content %}