softcore/rubrica/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.rubricas, name='rubricas'),
    path('<int:rubrica_id>/', views.ficha, name='ficha'),
    path('<int:rubrica_id>/edit/', views.edit_ficha, name='edit_ficha'),
    path('new/', views.new_ficha, name='new_ficha')
]

softcore/softcore/urls.py
from django.contrib import admin
from django.urls import include, path
from rubrica.views import AdminPageView

urlpatterns = [
    path('evaluadores/', include('usuarios.urls', namespace='evaluador')),
    path('evaluaciones/', include('evaluacion.urls')),
    path('rubricas/', include('rubrica.urls')),
    path('admin/', admin.site.urls),
    path('', AdminPageView.as_view(), name='index'),
]

softcore/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path('', views.evaluadores, name='evaluadores'),
    path('eliminar/<int:pk>/', views.eliminar_evaluador, name='eliminar_evaluador'),
]

softcore/rubrica/models.py
from django.db import models
from django.db.models.query_utils import Q

class Rubrica(models.Model):
    tipo = models.CharField(max_length=2)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        constraints = [
            # las rubricas template no pueden tener
            # nombres repetidos (pero las instancias si)
            models.UniqueConstraint(
                fields=['nombre'],
                condition=Q(tipo='PL'),
                name='unique_PL_nombre'
            ),
            # las rubricas solo pueden ser de tipo PL o IN
            models.CheckConstraint(check=Q(tipo='PL')|Q(tipo='IN'), name='tipo_PL_IN')
        ]

class Criterio(models.Model):
    rubrica = models.ForeignKey(Rubrica, on_delete=models.CASCADE)
    texto = models.CharField(max_length=350)

    def __str__(self):
        return self.texto[:25]

class NivelCumplimiento(models.Model):
    criterio = models.ForeignKey(Criterio, on_delete=models.CASCADE)
    puntaje = models.FloatField(default=0)
    texto = models.CharField(max_length=350)

    def __str__(self):
        return self.texto[:25]
    
    class Meta:
        ordering = ['-puntaje']
        

softcore/rubrica/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
import json as json


from .models import Rubrica, Criterio, NivelCumplimiento

# Create your views here.


class AdminPageView(TemplateView):
	template_name = 'index.html'

def rubricas(request):
	if request.method == "POST":
		rubricaId = int(request.POST['id'])
		rubrica = get_object_or_404(Rubrica, pk=rubricaId)
		rubrica.delete()
	rubricas_list = Rubrica.objects.order_by('-id')
	context = {'rubricas_list': rubricas_list}
	return render(request, 'rubrica/rubricas.html', context)

def ficha(request, rubrica_id):
	rubrica = get_object_or_404(Rubrica, pk=rubrica_id)
	criterios = Criterio.objects.filter(rubrica=rubrica_id)
	max_puntaje = 0
	critKey = criterios.first().id
	#aca se buscan todos los niveles de aprobacion
	for crit in criterios:
		#se sabe que el primer elemento que se saque de NivelCumplimiento es el mayor posible
		temp = NivelCumplimiento.objects.filter(criterio = crit.id).first()
		if(temp.puntaje >= max_puntaje):
			max_puntaje = temp.puntaje
			critKey = crit.id

	niveles = NivelCumplimiento.objects.filter(criterio=critKey)
	#el contexto lleva la rubrica en cuestion, un set de niveles que es la primera file de la tabla
	#ademas de los criterios a partir de los cuales se contruye el resto de la tabla
	#de esta forma el manejo de la contruccion en el template es mas limpio
	return render(request, 'rubrica/ficha_rubrica.html', {'rubrica': rubrica, 'criterios': criterios, 'niveles':niveles})

def edit_ficha(request, rubrica_id):
	if request.method == "POST":
		data = json.loads(request.body)
		rubricasWithName = Rubrica.objects.filter(nombre=data['nombre'])
		print("las rubricas con el nombre 5 que trae el post son: ", rubricasWithName)
		print("el nombre de la rubrica es: ", data['nombre'])
		print("el id de la rubrica es: ", data['id'])
		#print("las condiciones del if son: ", len(rubricasWithName), rubricasWithName[0].id, rubricasWithName[0].id == int(data['id']))
		if(len(rubricasWithName) == 0 or rubricasWithName[0].id == int(data['id'])):
			
			rubrica = get_object_or_404(Rubrica, pk=int(data['id']))
			rubrica.delete()
			rubrica = Rubrica()
			print(rubrica.id)
			rubrica.id = int(data['id'])
			rubrica.nombre = data['nombre']
			rubrica.tipo = "PL"
			rubrica.save()

			puntajes=data['filas'][0]

			for fila in data['filas'][1:]:
				nuevoCrit = Criterio()
				nuevoCrit.rubrica = rubrica
				nuevoCrit.texto = fila[0]
				nuevoCrit.save()
				for i in range(1,len(fila)):
					nuevoNivel = NivelCumplimiento(criterio=nuevoCrit, texto=fila[i], puntaje=float(puntajes[i]))
					nuevoNivel.save()


	rubrica = get_object_or_404(Rubrica, pk=rubrica_id)
	criterios = Criterio.objects.filter(rubrica=rubrica_id)
	max_puntaje = 0
	critKey = criterios.first().id
	#aca se buscan todos los niveles de aprobacion
	for crit in criterios:
		#se sabe que el primer elemento que se saque de NivelCumplimiento es el mayor posible
		temp = NivelCumplimiento.objects.filter(criterio = crit.id).first()
		if(temp.puntaje >= max_puntaje):
			max_puntaje = temp.puntaje
			critKey = crit.id

	niveles = NivelCumplimiento.objects.filter(criterio=critKey)
	#el contexto lleva la rubrica en cuestion, un set de niveles que es la primera file de la tabla
	#ademas de los criterios a partir de los cuales se contruye el resto de la tabla
	#de esta forma el manejo de la contruccion en el template es mas limpio
	return render(request, 'rubrica/edit_ficha.html', {'rubrica': rubrica, 'criterios': criterios, 'niveles':niveles, 'rubricas': Rubrica.objects.all()})

def new_ficha(request):
	if request.method == "POST":
		data = json.loads(request.body)
		rubricasWithName = Rubrica.objects.filter(nombre=data['nombre'])
		if(len(rubricasWithName) == 0):
			newRubrica = Rubrica(tipo="PL", nombre=data['nombre'])
			newRubrica.save()
		
			puntajes=data['filas'][0]

			for fila in data['filas'][1:]:
				nuevoCrit = Criterio()
				nuevoCrit.rubrica = newRubrica
				nuevoCrit.texto = fila[0]
				nuevoCrit.save()
				for i in range(1,len(fila)):
					nuevoNivel = NivelCumplimiento(criterio=nuevoCrit, texto=fila[i], puntaje=float(puntajes[i]))
					nuevoNivel.save()
		return render(request, 'rubrica/new_ficha.html', {'rubricas': Rubrica.objects.all()})
	else:
		return render(request, 'rubrica/new_ficha.html', {'rubricas': Rubrica.objects.all()})

softcore/rubrica/templates/rubrica/edit_ficha.html
<!DOCTYPE html>

<html lang="es">
<title>Ingeniería de Software</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <!--Profile image -->
  <div class="w3-container">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:200px;width:200px" alt="Avatar"></p>
    <h3 class="w3-padding-64"><center><b>Usuario</b></center></h3>
  </div>
  <div class="w3-bar-block">
    <a href="#" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="#showcase" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="#services" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
      <a href="#designers" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
    <a href="#designers" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Company Name</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">



    {% if rubrica %}
    <div id="titulo"><h1 class="w3-xxxlarge w3-text-red" style="margin: 2%;"><b>{{ rubrica.nombre }}</b></h1></div>
    {% else %}
    <div id="titulo"><h1 class="w3-xxxlarge w3-text-red" style="margin: 2%;"><b> invalid_title </b></h1></div>
    {% endif %}

  <!DOCTYPE html>
  <div class="w3-row w3-container">
    <div class="w3-col">
      <head>
        <style>
          .button2 {
            background-color: #c6bdbb; /* Green */
            border: none;
            color: black;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 0.2px 2px;
            cursor: pointer;
          }

          .button2 {width: 50%; border-radius: 12px;}
          .button2.button2:hover {background-color: #FFA07A;}


        </style>
      </head>
      <body>
        <button class="button2 button2" onclick="cambiarTitulo('titulo')">Título de la rúbrica<i class="fas fa-edit"></i></button><br>
      </body>
    </div>

    <div class = "w3-col" align="right">
      <head>

        <style>
          body {font-family: Arial, Helvetica, sans-serif;}

          .form-inline label {
            margin: 5px 0 5px 0;
          }

          .form-inline input {
            vertical-align: middle;
            margin: 5px 10px ;
            padding: 5px;
            width: 10%;
            background-color: #fff;
            border: 1px solid #ddd;
          }

          .form-inline button {
            padding: 5px 10px;
            background-color: #c6bdbb;
            border: none;
            color: black;
            cursor: pointer;
            border-radius: 8px;
          }

          .form-inline button:hover {
            background-color: #FFA07A;
          }


        </style>
      </head>
    </div>
  </div>


  <head>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        cursor: pointer;
        margin: 10px 0.5% 0.5%;
      }

      td, th {
        border: 1px solid #665f5f;
        text-align: left;
        width: 20%;
        padding: 2.3%;
      }

      tr:nth-child(even) {
        background-color: #FFA07A;
      }
    </style>
  </head>
  <body>
  <table id="myTable">
    {% if rubrica %}
    <tr>
      <th></th>
      {% for nivel in niveles.reverse %}
      <th><div contenteditable="true">{{ nivel.puntaje }}</div></th>
      {% endfor %}
    </tr>
    {% for criterio in criterios %}
    <tr>
      <td><div contenteditable="true">{{ criterio.texto }}</div></td>
      {% with niveles=criterio.nivelcumplimiento_set.all %}
      {% for nivel in niveles.reverse %}
      <td><div contenteditable="true">{{ nivel.texto }}</div></td>
      {% endfor %}
      {% endwith %}
    </tr>
    {% endfor %}
    {% endif %}
  </table>
  </body>

  <div>
    <head>
      <style>
        .btn-group .button {
          background-color: #c6bdbb;
          border: none;
          color: black;
          padding: 15px 4.6%;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          cursor: pointer;
          float: left;
          margin: 18px 2%;
        }

        .btn-group .button { border-radius: 12px;}

        .btn-group .button:hover { background-color: #FFA07A; }

      </style>
    </head>
    <body>
      <div class="btn-group">
        <button class="button" onclick="addRow('myTable')">Agregar fila  <i class="fas fa-plus"></i></button>
        <button class="button" onclick="addColumn('myTable')">Agregar columna  <i class="fas fa-plus"></i></button>
        <button class="button" onclick="removeRow('myTable')">Borrar fila  <i class="fas fa-trash"></i></button>
        <button class="button" onclick="removeColumn('myTable')">Borrar columna  <i class="fas fa-trash"></i></button>
      </div>
    </body>
  </div>

  <head>
    <style>
    .button1 {
      background-color: #BF1010;
      border: none;
      color: white;
      padding: 45px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 10px 78%;
      cursor: pointer;
    }

    .button1 {border-radius: 12px;}
    .button1.button1:hover {background-color: #FFA07A;}

    </style>
  </head>
  <body>
    <button class="button1 button1" onclick="postTable('myTable')">Guardar rúbrica <i class="far fa-save"></i></button>
  </body>



<!-- End page content -->
</>

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>

<script>

var rubrics = {};
{% if rubricas %}
{% for rubric in rubricas %}
  rubrics["{{ rubric.id }}"] = "{{ rubric.nombre }}";
{% endfor %}
{% endif %}

// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

function addRow(tableId){
  var table = document.getElementById(tableId);
  var row = table.insertRow(-1);
  var i;
  for (i = 0; i<table.rows[0].cells.length; i++){
    var cell = row.insertCell(i);
    if(i == 0){
      cell.innerHTML = "<div contenteditable='true'> Edit criterio</div>"
    }else{
      cell.innerHTML = "<div contenteditable='true'> Edit celda</div>"
    }
  }
}

function removeRow(tableId){
  var table = document.getElementById(tableId);
  if(table.rows.length>2){
    table.deleteRow(table.rows.length - 1);
  }
}

function addColumn(tableId){
  var table = document.getElementById(tableId);
  var i;
  for(i = 0; i<table.rows.length; i++){
    var indice = table.rows[i].cells.length;
    cell = table.rows[i].insertCell(indice);
    if(i == 0){
      cell.innerHTML = "<div contenteditable='true'> Edit ptje</div>"
    }else{
      cell.innerHTML = "<div contenteditable='true'> Edit celda</div>"
    }
  }
}

function removeColumn(tableId){
  var table = document.getElementById(tableId);
  var i;
  if(table.rows[0].cells.length > 2){
    for(i=0; i<table.rows.length; i++){
      var indice = table.rows[i].cells.length - 1;
      table.rows[i].deleteCell(indice); 
    }
  }
}

//Funcion que valida en primera instancia que los campos de la tabla sean correctos
  function tableIsValid(tableId, tableTitle, rubricaId) {
    var table = document.getElementById(tableId);
    var i;
    var prev = 0;
    var ptjes = [];
    for (var key in rubrics) {
      if (rubrics[key] == tableTitle && key != rubricaId) {
        alert("El nombre de la rubrica ya esta en uso");
        return false;
      }
    }
    for (i = 1; i < table.rows[0].cells.length; i++) {
      var str = table.rows[0].cells[i].innerHTML;
      var length = str.length;
      var res = str.substring(28, length - 6);
      if (isNaN(Number(res))) {
        alert("Las casillas de puntajes solo pueden contener caracteres numericos");
        return false;
      }
      if (Number(res) < prev) {
        alert("Los puntajes deben ser ascendentes hacia la derecha");
        return false;
      }
      ptjes.push(Number(res));
      prev = Number(res);
    }
    var maxPuntaje = 0;
    for (i = 1; i < table.rows.length; i++) {
      var str = table.rows[i].cells[0].innerHTML;
      var length = str.length;
      var res = str.substring(28, length - 6);
      if (res == "") {
        alert("Todas las casillas de criterio deben tener un texto");
        return false;
      }
      var j = 1;
      for (j; j < table.rows[i].cells.length; j++) {
        var str2 = table.rows[i].cells[j].innerHTML;
        var length2 = str2.length;
        var res2 = str2.substring(28, length2 - 6);
        if (res == "" && res2 != "") {
          alert("Un criterio no puede saltarse puntajes")
          return false;
        }
        if (res2 == "" && res != "") {
          maxPuntaje += ptjes[j - 2]
        }
        if (j == table.rows[i].cells.length - 1 && res2 != "") {
          maxPuntaje += ptjes[j - 1]
        }
        res = res2;
      }
    }
    if (maxPuntaje != 6) {
      alert("La suma de puntajes maximos obtenidos en cada criterio debe ser exactamente 6")
      return false;
    }

    return true;

  }

  function postTable(tableId) {
    var table = document.getElementById(tableId);
    var titulo = document.getElementById("titulo");
    var nombre = titulo.innerHTML.substring(59, titulo.innerHTML.length - 9);
    var filas = [];
    var rubricaId = "{{ rubrica.id }}";
    var i;
    if (tableIsValid(tableId, nombre, rubricaId)) {
      for (i = 0; i < table.rows.length; i++) {
        var j;
        var fila = [];
        for (j = 0; j < table.rows[i].cells.length; j++) {
          var str = table.rows[i].cells[j].innerHTML;
          var length = str.length;
          var res = str.substring(28, length - 6);
          fila.push(res);
        }
        filas.push(fila);
      }
      var token = '{{ csrf_token }}';
      $.ajax({
        headers: { "X-CSRFToken": token },
        url: '',
        type: 'POST',
        data: JSON.stringify({
          'filas': filas, 'nombre': nombre, 'id': rubricaId,
        }),
      });
      alert("Rubrica editada, volviendo a /rubricas/");
      window.location.href = "/rubricas/"
    }

  }

  function cambiarTitulo(tituloId) {
    var titulo = document.getElementById(tituloId);
    var prevTitle = titulo.innerHTML
    var name = prompt("Ingrese nombre para la ficha rubrica, no puede incluir espacios", "nombre_ficha");
    if (name != null && name != "") {
      titulo.innerHTML = '<h1 class="w3-xxxlarge w3-text-red" style="margin: 2%;"><b>' + name + '</b></h1>';
    }
  }

</script>

</body>
</html>

softcore/rubrica/templates/rubrica/rubricas.html
<!DOCTYPE html>
<html lang="es">
<title>Plataforma de evaluación-Rúbricas</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <!--Profile image -->
  <div class="w3-container">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:200px;width:200px" alt="Avatar"></p>
    <h3 class="w3-padding-64"><center><b>Usuario</b></center></h3>
  </div>
  <div class="w3-bar-block">
    <a href="#" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="#showcase" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="{% url 'evaluador:evaluadores' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
    <a href="{% url 'rubricas' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
    <a href="#designers" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Usuario</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px"

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Rúbricas</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

<div class="w3-container">
  <form method="get" action="{% url 'new_ficha' %}">
    <button class="w3-button w3-large w3-red w3-right w3-round">Agregar nueva rúbrica</button><br>
  </form>
</div>
<!--Seccion rubricas-->

{% if rubricas_list %}

  {% for rubrica in rubricas_list %}
    <button onclick="myFunction('Demo{{ rubrica.id }}')" class="w3-btn w3-red w3-block w3-margin" style="width: 75%">
      <h3>
        {{ rubrica.nombre }}</h3>
    </button>
    
    <div id="Demo{{ rubrica.id }}" class="w3-hide w3-container w3-pale-red w3-center w3-padding-large w3-margin" style="width: 75%">
      <p>
        {% for criterio in rubrica.criterio_set.all %}
        <li>{{ criterio.texto }}</li>
        {% endfor %}
      </p>
      <div class="w3-container">
        <form method="get" action="{% url 'ficha' rubrica.id %}">
          <button type="submit" class="w3-button w3-large w3-margin-right w3-red w3-left w3-round">Ver</button>
        </form>
        <form method="get" action="{% url 'edit_ficha' rubrica.id %}">
          <button class="w3-button w3-large w3-red w3-left w3-round">Modificar</button>
        </form>
        <form method="post" action="">
          {% csrf_token %}
          <button type="submit" class="w3-button w3-large w3-red w3-right w3-round", name="id", value= "{{ rubrica.id }}">Eliminar</button>
        </form>
      </div>
    </div>
  {% endfor %}

{% else %}

{% endif %}

<!--
<button onclick="myFunction('Demo3')" class="w3-btn w3-red w3-block w3-margin" style="width: 75%"><h3>
    Rúbrica 1</h3></button>

<div id="Demo3" class="w3-hide w3-container w3-pale-red w3-center w3-padding-large w3-margin"style="width: 75%">
  <p><li>Aspecto 1</li>
    <li>Aspecto 2</li>
</p>
    <div class="w3-container">
      <button class="w3-button w3-large w3-margin-right w3-red w3-left w3-round">Ver</button>
  <button class="w3-button w3-large w3-red w3-left w3-round">Modificar</button>
  <button class="w3-button w3-large w3-red w3-right w3-round">Eliminar</button>
</div>
</div>

<button onclick="myFunction('Demo4')" class="w3-btn w3-red w3-block w3-margin" style="width: 75%"><h3>
    Rúbrica 2</h3></button>

<div id="Demo4" class="w3-hide w3-container w3-pale-red w3-center w3-padding-large w3-margin"style="width: 75%">
  <p><li>Aspecto 1</li>
    <li>Aspecto 2</li>
</p>
    <div class="w3-container">
      <button class="w3-button w3-large w3-margin-right w3-red w3-left w3-round">Ver</button>
  <button class="w3-button w3-large w3-red w3-left w3-round">Modificar</button>
  <button class="w3-button w3-large w3-red w3-right w3-round">Eliminar</button>
</div>
</div>
-->



</div>

<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}



</script>

</body>
</html>